### ISSUE TITLE
[OTHER] Help with Media Player after upgrade to 4.0.85

### ISSUE THREAD

**Issue by smulvih2** [wet-boew/wet-boew#9945]
I recently upgraded my site from wet-boew/wet-boew `4.0.43.1` to `4.0.85`, and now the site is experiencing a weird behaviour with the Media Player. This was working as expected before the upgrade.

The issue, is for some users the media player works as expected, for others they get a JS error in the console and the media player does not load. In this case, the YouTube thumbnail is blank and the users sees an "undefined" label in place of the video.

![Image](https://github.com/user-attachments/assets/2b079752-0d73-40f0-9261-4f3fc83cae64)

See the issue here - [https://guide-alimentaire-stage.hpfb-dgpsa.ca/fr/conseils-pour-alimentation-saine/utilisez-assiette-du-guide-alimentaire-canadien-pour-preparer](https://guide-alimentaire-stage.hpfb-dgpsa.ca/fr/conseils-pour-alimentation-saine/utilisez-assiette-du-guide-alimentaire-canadien-pour-preparer)

The English side seems to work for most people, but the French side is where we are seeing this more often. On my Government laptop, I am not able to reproduce the issue. On my personal laptop I am seeing the error.

Wondering if anyone can spot what might be causing this issue?

**Comment by smulvih2** [comment]
JS error in console:

Error 1:
`Uncaught tim: 'fs' not found in {{fs}}`

Error 2:
```
Uncaught TypeError: s.player is not a function
    at HTMLElement.<anonymous> (wet-boew.js:12648:36)
    at HTMLDocument.dispatch (jquery.min.js?v=3.7.1:2:40035)
    at HTMLDocument.<anonymous> (jquery.min.js?v=3.7.1:2:38006)
    at Object.trigger (jquery.min.js?v=3.7.1:2:70124)
    at HTMLIFrameElement.<anonymous> (jquery.min.js?v=3.7.1:2:70726)
    at ce.each (jquery.min.js?v=3.7.1:2:3129)
    at ce.each (jquery.min.js?v=3.7.1:2:1594)
    at ce.trigger (jquery.min.js?v=3.7.1:2:70701)
    at o (wet-boew.js:12124:7)
    at onReady (wet-boew.js:12341:6)
```

**Comment by smulvih2** [comment]
Ended up being browser cache. Not exactly sure why since the markup was correct and it was loading the proper JS file for `4.0.85`. Issue seems to occur when you load a page using `4.0.43.1`, then visiting another page using `4.0.85`. Could have also been caused partly by CloudFlare. Closing ticket as our issue has been resolved. Thanks!
